# Generated by Django 2.0 on 2017-12-10 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=64)),
                ('requester_email', models.EmailField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('b', 'Bug report'), ('f', 'Feature request'), ('o', 'Other')], max_length=1)),
                ('urgency', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('o', 'Open'), ('p', 'In Progress'), ('c', 'Complete'), ('r', 'Rejected')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
